### ISSUE TITLE
Optimization: Dynamic x-axis labels

### ISSUE THREAD

**Issue by haysarah** [regulatorystudies/Reg-Stats#42]
# The Goal
Write a function that calculates how to assign x-axis labels for charts that use years on the x-axis so that the value of the last year of data is always shown.

**Comment by pateldevenr** [comment]
My proposal:

# column_number must be the column on which the x-axis label will be based
xbreaks <- function(dataset, column_number){
  round(seq(min(dataset[column_number]), max(dataset[column_number]),
            by = (max(dataset[column_number])-min(dataset[column_number]))/11),0)
}

I have added this to the local_utils file.  My sample implementation on my own branch can be found here: [](https://github.com/regulatorystudies/Reg-Stats/commit/f91b4266dfadbd37ba27ae623c581e56eb1d94b7)

**Comment by mfebrizio** [comment]
Thanks, Deven. This looks great. Would you please be able to adjust this in the following way:

- move the function definition of xbreaks to just local_utils
- import the function in the Rmd scripts using source
- call the function as normal

Then there is only one function definition for xbreaks, so any modifications only need to be done in one place.

**Comment by pateldevenr** [comment]
Implemented here: https://github.com/regulatorystudies/Reg-Stats/commit/0b04c8a7ec5739da0bdf0a5bc7cdf486c48248f1
