### ISSUE TITLE
Decluttering: Cumulative Rules by Presidential Administration

### ISSUE THREAD

**Issue by haysarah** [regulatorystudies/Reg-Stats#43]
# The Challenge
The early months of the cumulative rules by presidential administration chart is a bit cluttered with overlapping lines. Research what other people have done to combat similar issues in charts that have lots of lines originating from the same point, and try it out in a new branch!

**Comment by henhirsch** [comment]
If we pursue the interactive dashboard idea for the Reg Stats graphics, this cluttering may cease to be an issue. Adding interactive time range functionality would enable a user to select as many months as they would like to display data for. This would let us combine the graphics for Cumulative ES Final Rules Published by Admin. and Cumulative ES Final Rules Published by Admin. in First Year into one dashboard. 

However, we may still want to add the option to display lines for selected presidents in color (while the lines for the unselected presidents remain greyed out).

**Comment by mfebrizio** [comment]
I think this is right. A dashboard with an interactive plot would make this relatively moot. The grayed out feature might be able to be integrated into the plots too.

**Comment by henhirsch** [comment]
I know this is an enterprise dashboard produced by professionals, but it does look like it's possible to toggle individual lines on and off for line graphs (I think R Shiny was used in this case). Also, I like ability to mouse over a line in a particular year and get the data for all selected lines in that year:

https://connect.appsilon.com/fresh-water-resources/

**Comment by henhirsch** [comment]
info on packages used:

https://www.appsilon.com/post/freshwater-dashboard-ui-ux-for-r-shiny-applications
