### ISSUE TITLE
Add preferred citation for Reg Stats webpage

### ISSUE THREAD

**Issue by mfebrizio** [regulatorystudies/Reg-Stats#47]
Something along the lines of:

> The George Washington University Regulatory Studies Center, "CHART OR DATASET TITLE," retrieved ACCESS DATE, go.gwu.edu/regstudies.

Or we could use the direct link to [Reg Stats](https://regulatorystudies.columbian.gwu.edu/reg-stats) or ask Nate to make a shortcut for Reg Stats (e.g., go.gwu.edu/regstats)

**Comment by zhoudanxie** [comment]
Just to add to this issue and remind ourselves:

We need to revise the intro on the Reg Stats webpage with the suggested citation and link to this Github repo.

I'll draft a revised intro and send it for review.

**Comment by zhoudanxie** [comment]
I suggest we modify the introduction text on the Reg Stats page to make it more focused and accurate. Below is the revised text. Please review and feel free to make any changes. @mfebrizio @haysarah

This page provides accessible charts and supporting data to better understand patterns and trends in federal rulemaking activities across presidential administrations, across agencies, and over time. The policy team at the Regulatory Studies Center updates these charts on a regular basis as new data are available.

The data and charts on this page have been featured in a number of publications. Please include an appropriate citation if you would like to use these files in your publication or presentation.

Suggested citation:

> The George Washington University Regulatory Studies Center, "CHART OR DATASET TITLE," retrieved ACCESS DATE, go.gwu.edu/regstudies.

All data and charts are also accessible on [Github](https://github.com/regulatorystudies/Reg-Stats).

If you would like to see us include other data or have questions about the information presented here, please email regulatorystudies@gwu.edu.

**Comment by mfebrizio** [comment]
Minor changes suggested:

> patterns and trends in federal rulemaking activities across presidential administrations, ~~across~~ **among** agencies, and over time.

> **The source code for** ~~all~~ data and charts are ~~also~~ accessible on [GitHub](https://github.com/regulatorystudies/Reg-Stats).

Otherwise, this looks excellent! Much clearer.

**Comment by haysarah** [comment]
One small suggestion from me as well (to be a little more concise): 

> This page provides accessible charts and supporting data to ~~better understand~~ **highlight** patterns and trends 

And quick grammar fix in Mark's suggested edit:

> The source code for all data and charts ~~are~~ **is** also accessible on [GitHub](https://github.com/regulatorystudies/Reg-Stats).

Otherwise looks great - thanks for drafting that, Zoey!

**Comment by zhoudanxie** [comment]
Thank you both @mfebrizio @haysarah ! I will send the revised language to Nate.

**Comment by mfebrizio** [comment]
Thanks, Zoey! If it would help on his end, I can update the website text if
he approves it.

Mark Febrizio
*Senior Policy Analyst* | Regulatory Studies Center
<https://regulatorystudies.columbian.gwu.edu/>
The George Washington University
***@***.***
