### ISSUE TITLE
Create R code for monthly ES rules chart

### ISSUE THREAD

**Issue by zhoudanxie** [regulatorystudies/Reg-Stats#62]
@pateldevenr Do you have time to create the R code for plotting the new monthly economically significant rules chart? The current chart was created using Excel: https://github.com/regulatorystudies/Reg-Stats/tree/main/data/monthly_es_rules. It would be great to have R code for this one as well. Thanks!

**Comment by pateldevenr** [comment]
I can start working on this!

**Comment by zhoudanxie** [comment]
We only need a chart for the Biden administration for now, like the one created with Excel in the folder. Thanks @pateldevenr @henhirsch !

**Comment by mfebrizio** [comment]
#61 finished with PR
