### ISSUE TITLE
Revise R code for the Unified Agenda chart

### ISSUE THREAD

**Issue by zhoudanxie** [regulatorystudies/Reg-Stats#89]
@henhirsch There is an issue with the Unified Agenda chart. Would you be available to work on this?

I have updated the data for the Spring 2024 UA data. I ran the R code to update the chart, but the Spring 2024 bar is wider than the others (see below). It looks like it's taking the space for both spring and fall. If you are available, would you please investigate the code and revise it as necessary @henhirsch ?

![active_actions_by_unified_agenda](https://github.com/regulatorystudies/Reg-Stats/assets/37126521/2aecbb14-23e3-462e-9c9d-b4d75513ac73)

**Comment by henhirsch** [comment]
Will do!

**Comment by zhoudanxie** [comment]
Looks good! Thanks for working on this. I think there are two separate minor issues we need to fix. Can you please work on these too?

- Remove "Season" from the legend and make the text "Spring" and "Fall" bigger
- Change the Note text to:

> Note: Only one agenda was published in 1995 and 2012. Active actions refer to rulemakings in a pre-rule, proposed rule or final rule stage as indicated by the Unified Agenda.

- Align the Note to the left if it looks better.

Let me know if you have other suggestions.

**Comment by mfebrizio** [comment]
> Only one agenda was published in 1995 and 2012.

Jumping in here: there were two UAs published in 1995, but Reginfo only has the Fall edition available. I think Susan knows when the the first UA was issued, but govinfo at least has the [Spring 1995 edition](https://www.govinfo.gov/collection/unified-agenda?path=/gpo/Unified%20Agenda/1995).

In light of that, the earlier version of the note might be more accurate.

**Comment by zhoudanxie** [comment]
Thanks for correcting this, Mark! Then the updated Note should be:

> Note: Only the Fall Agenda is available for 1995, and only one Agenda was published in 2012. Active actions refer to rulemakings in a pre-rule, proposed rule or final rule stage as indicated by the Unified Agenda.

**Comment by henhirsch** [comment]
What do you guys think? Is there too much going on below the graph? And which alignment do you prefer?

<img width="1087" alt="Screenshot 2024-07-11 at 15 06 08" src="https://github.com/regulatorystudies/Reg-Stats/assets/122999149/5656d0bb-2f71-405b-9950-0583b505367c">

<img width="1087" alt="Screenshot 2024-07-11 at 15 09 16" src="https://github.com/regulatorystudies/Reg-Stats/assets/122999149/8a532c63-2da7-4171-92f9-64a50f10ca0a">

**Comment by zhoudanxie** [comment]
I think it looks great! I prefer the first one (aligned left).
